[build]
  command = "npm run build"
  publish = "build"

# Frontend -> Backend proxy:
# POST /api/enquiries (on the FE site) -> /.netlify/functions/api/enquiries (on the BE site)
[[redirects]]
  from = "/api/*"
  to   = "https://srilakshmipowerprintersbe.netlify.app/.netlify/functions/api/:splat"
  status = 200
  force  = true
